#pragma kernel cull

#pragma multi_compile_local _ VOXEL_INSTANCE
#pragma multi_compile_local _ VOXEL_ORTHOGRAPHIC

#include "VoxelStructs.cginc"


uniform float4 cameraFarPlane; // x,y,z: normal, w: distance
uniform float4 cameraLeftPlane;
uniform float4 cameraRightPlane;
uniform float4 cameraDownPlane;
uniform float4 cameraUpPlane;
#ifndef VOXEL_ORTHOGRAPHIC
uniform float4 cameraPosition; // x,y,z: position
#endif
#ifndef VOXEL_INSTANCE
uniform uint nChunks;
#endif

StructuredBuffer<VoxelChunk> chunks; // Input: chunks
RWStructuredBuffer<uint> commands; // Output: indirect arguments
RWStructuredBuffer<CommandOffset> offsets; // Output: offsets
StructuredBuffer<float4x4> transforms; // Input: transform of each instance
RWStructuredBuffer<float4x4> renderedTransforms; // Output: transform of each rendered instance


void addCommand(uint indexCountPerInstance, uint instanceCount, uint startIndex, uint baseVertexIndex, uint startInstance, CommandOffset offset) {
    uint cmd = offsets.IncrementCounter();
    commands[cmd * 5] = indexCountPerInstance;
    commands[cmd * 5 + 1] = instanceCount;
    commands[cmd * 5 + 2] = startIndex;
    commands[cmd * 5 + 3] = baseVertexIndex;
    commands[cmd * 5 + 4] = startInstance;
    offsets[cmd] = offset;
}


bool outsidePlane(float3 center, float3 size, float4 plane, float4x4 transform) {
    plane = mul(plane, transform);
    float3 normalSign = sign(plane.xyz);
    float3 closestPoint = center + size * normalSign;
    return dot(float4(closestPoint, 1), plane) < 0;
}


// Ignore chunks outside of camera view
bool boundsCulling(float3 center, float3 size, float4x4 transform) {
    return !(
        outsidePlane(center, size, cameraFarPlane, transform) ||
        outsidePlane(center, size, cameraLeftPlane, transform) ||
        outsidePlane(center, size, cameraRightPlane, transform) ||
        outsidePlane(center, size, cameraUpPlane, transform) ||
        outsidePlane(center, size, cameraDownPlane, transform)
    );
}


// Ignore chunks that are invisible because of their normal
bool normalCulling(float3 center, float3 size, uint normalID, float4x4 transform) {
    if (normalID == NORMAL_ANY) return true;
    else {
        float3 normal = getNormal(normalID);
        normal = mul(transform, float4(normal, 0)).xyz;
#ifdef VOXEL_ORTHOGRAPHIC
        return dot(cameraFarPlane.xyz, normal) > 0.0001;
#else
        float3 back = center - normal * size;
        back = mul(transform, float4(back, 1)).xyz;
        return dot(back - cameraPosition.xyz, normal) < 0;
#endif
    }
}


#ifdef VOXEL_INSTANCE

#define GROUP_SIZE 64

groupshared uint sum[GROUP_SIZE];

[numthreads(GROUP_SIZE, 1, 1)]
void cull(uint3 group : SV_GroupID, uint thread : SV_GroupThreadID) {
    VoxelChunk chunk = chunks[group.x];
    uint count = 0;

    // Add instances to renderedTransforms
    for (uint i = 0; i < chunk.instanceCount; i += GROUP_SIZE) {
        bool add = 0;
        float4x4 transform = 0;
        if (i + thread.x < chunk.instanceCount) {
            transform = transforms[chunk.startInstance + i + thread.x];
            add = normalCulling(chunk.center, chunk.size, chunk.normal, transform) && boundsCulling(chunk.center, chunk.size, transform);
        }
        
        // Prefix sum
        sum[thread.x] = add;
        GroupMemoryBarrierWithGroupSync();
        for (int bit = 1; bit < GROUP_SIZE; bit <<= 1) {
            if (thread.x & bit) sum[thread.x] += sum[(thread.x & -bit) - 1];
            GroupMemoryBarrierWithGroupSync();
        }

        if (add) renderedTransforms[chunk.startRenderedInstance + count + sum[thread.x] - 1] = transform;
        count += sum[GROUP_SIZE - 1];
    }

    // Add command if some instances were added
    if (thread.x == 0 && count > 0) {
        addCommand(chunk.faceCount * 6, count, 0, chunk.startFace * 4, chunk.startRenderedInstance, chunk.offset);
    }
}

#else

[numthreads(64, 1, 1)]
void cull(uint3 id : SV_DispatchThreadID) {
    if (id.x < nChunks) {
        VoxelChunk chunk = chunks[id.x];
        float4x4 transform = transforms[chunk.startInstance];
        if (normalCulling(chunk.center, chunk.size, chunk.normal, transform) && boundsCulling(chunk.center, chunk.size, transform)) {
            addCommand(chunk.faceCount * 6, 1, 0, chunk.startFace * 4, chunk.startInstance, chunk.offset);
            renderedTransforms[chunk.startInstance] = transform;
        }
    }
}

#endif